### ISSUE TITLE
Добавить правило на размер отступов (indentation_width)

### ISSUE THREAD

**Issue by petropavel13** [TouchInstinct/BuildScripts#183]
Надо проверить, что работает корректно и включить в конфиг

**Comment by Loupehope** [comment]
Не работает для нашего форматирования параметров функции. Надо так (что и советуют [кодстайлы](https://github.com/raywenderlich/swift-style-guide#function-declarations)): 
<img width="479" alt="Screenshot 2020-09-17 at 22 25 54" src="https://user-images.githubusercontent.com/31570429/93517999-e3948b00-f934-11ea-85af-07778e34759c.png">
У нас так:
<img width="764" alt="Screenshot 2020-09-17 at 22 26 46" src="https://user-images.githubusercontent.com/31570429/93518015-e98a6c00-f934-11ea-9fee-49f929470ce9.png">
