### ISSUE TITLE
Добавить скрипт проверки наличия локализации на все поддерживаемые языки

### ISSUE THREAD

**Issue by petropavel13** [TouchInstinct/BuildScripts#184]
Например так: https://blog.kulman.sk/checking-for-missing-translations-in-ios/
или так: https://github.com/samdmarshall/nslocalizer
или ещё погуглить

**Comment by Loupehope** [comment]
https://drobinin.com/posts/verifying-localisation-in-ios-apps-with-github-actions-the-reinvented-wheel/
