### ISSUE TITLE
Добавить правило на стиль написания switch case с параметрами

### ISSUE THREAD

**Issue by petropavel13** [TouchInstinct/BuildScripts#185]
Должно быть

```swift
case let .value(param1, param2)
```
но не 
```swift
case .value(let param1, let param2)
```

**Comment by mrtokii** [comment]
У нас в конфигурации уже включено _pattern_matching_keywords_

![telegram-cloud-photo-size-2-5278707234660003470-y](https://user-images.githubusercontent.com/15659755/80530974-82c6df00-89a2-11ea-8bb6-227705e7d34a.jpg)

**Comment by petropavel13** [comment]
значит это на не наших проектах я увидел

**Comment by petropavel13** [comment]
в SwiftLint не работает если один параметр
